

class language_CN:
	message_1 = "welcome to PhonixBuilder"
	ACME_FailedToGetCommand=             "未能读取ACME命令"
	ACME_FailedToSeek=                   "无效ACME文件，因为seek操作失败了。"
	ACME_StructureErrorNotice=           "文件结构错误"
	ACME_UnknownCommand=                 "未知ACME命令（文件错误）"
	Auth_BackendError=                   "后端错误"
	Auth_FailedToRequestEntry=           "未能请求租赁服入口，请检查租赁服等级设置是否关闭及租赁服密码是否正确。"
	Auth_HelperNotCreated=               "辅助用户尚未创建，请前往用户中心进行创建。"
	Auth_InvalidFBVersion=               "FastBuilder 版本无效，请更新。"
	Auth_InvalidHelperUsername=          "辅助用户的用户名无效，请前往用户中心进行设置。"
	Auth_InvalidToken=                   "无效Token，请重新登录。"
	Auth_InvalidUser=                    "无效用户，请重新登录。"
	Auth_ServerNotFound=                 "租赁服未找到，请检查租赁服是否对所有人开放。"
	Auth_UnauthorizedRentalServerNumber= "对应租赁服号尚未授权，请前往用户中心进行授权。"
	Auth_UserCombined=                   "该用户已经合并到另一个账户中，请使用新账户登录。"
	Auth_FailedToRequestEntry_TryAgain=  "未能请求租赁服入口，请稍后再试。"
	BDump_Author=                        "作者"
	BDump_EarlyEOFRightWhenOpening=      "未能读取文件，因为文件过早结束，可能已经损坏。"
	BDump_FailedToGetCmd1=               "未能获取到 cmd[pos=0] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd2=               "未能获取到 cmd[pos1] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd4=               "未能获取到 cmd[pos2] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd6=               "未能获取到 cmd[pos3] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd7_0=             "未能获取到 cmd[pos4] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd7_1=             "未能获取到 cmd[pos5] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd10=              "未能获取到 cmd[pos6] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd11=              "未能获取到 cmd[pos7] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetCmd12=              "未能获取到 cmd[pos8] 的任何参数，文件可能已经损坏"
	BDump_FailedToGetConstructCmd=       "未能获取到构建命令，文件可能已经损坏"
	BDump_FailedToReadAuthorInfo=        "未能读取作者信息，文件可能已损坏"
	BDump_FileNotSigned=                 "文件未签名"
	BDump_FileSigned=                    "文件已签名，持有者：%s"
	BDump_NotBDX_Invheader=              "不是bdx文件（无效文件头）"
	BDump_NotBDX_Invinnerheader=         "不是bdx文件（无效内部文件头）"
	BDump_SignedVerifying=               "文件已签名，正在验证..."
	BDump_VerificationFailedFor=         "因 %v 未能验证文件签名。"
	BDump_Warn_Reserved=                 "警告：BDump/Import：使用了保留字段\n"
	CommandNotFound=                     "未能找到此命令"
	ConnectionEstablished=               "成功连接到服务器。"
	Copyright_Notice_Bouldev=            "版权所有 (c) FastBuilder DevGroup Bouldev 2022"
	Copyright_Notice_Contrib=            "代码参与= Ruphane CAIMEO CMA2401PT"
	Crashed_No_Connection=               "较长时间内未能建立连接"
	Crashed_OS_Windows=                  "按ENTER（回车）键来退出程序。"
	Crashed_StackDump_And_Error=         "Stack dump 于上方显示。错误为："
	Crashed_Tip=                         "FastBuilder Phoenix 运行过程遇到问题"
	CurrentDefaultDelayMode=             "目前默认延迟模式"
	CurrentTasks=                        "任务列表："
	DelayModeSet=                        "延迟模式已设定"
	DelayModeSet_DelayAuto=              "延迟值已自动设置为: %d"
	DelayModeSet_ThresholdAuto=          "延迟阈值已自动设置为: %d"
	DelaySet=                            "延迟已设定"
	DelaySetUnavailableUnderNoneMode=    "[delay set] 于 none 模式下不可用"
	DelayThreshold_OnlyDiscrete=         "延迟阈值只可在 discrete 模式下被设置。"
	DelayThreshold_Set=                  "延迟阈值已设置为 %d"
	ERRORStr=                            "错误"
	EnterPasswordForFBUC=                "请输入你的FastBuilder用户中心登录密码(不会显示): "
	Enter_FBUC_Username=                 "输入你的FastBuilder用户中心用户名: "
	Enter_Rental_Server_Code=            "请输入租赁服号: "
	Enter_Rental_Server_Password=        "输入租赁服密码 (如果没有设置则直接按[Enter] 输入不会回显): "
	ErrorIgnored=                        "已忽略此错误"
	Error_MapY_Exceed=                   "使用立体地图画时，MapY 应为范围在 20 至 255 的值（您输入的值为 %v)"
	FBUC_LoginFailed=                    "FastBuilder用户中心的用户名或密码无效"
	FBUC_Token_ErrOnCreate=              "创建Token文件时出错："
	FBUC_Token_ErrOnGen=                 "生成临时Token时出错"
	FBUC_Token_ErrOnRemove=              "未能删除token文件= %v"
	FBUC_Token_ErrOnSave=                "保存Token时出错："
	FileCorruptedError=                  "文件已被损坏"
	Get_Warning=                         "get命令已被set命令取代，未来将移除此命令，请迁移至set"
	IgnoredStr=                          "已忽略"
	InvalidFileError=                    "无效文件"
	InvalidPosition=                     "未获取到有效坐标。（可忽略此错误）"
	Lang_Config_ErrOnCreate=             "创建语言配置文件时出错：%v"
	Lang_Config_ErrOnSave=               "保存语言配置时出错：%v"
	LanguageName=                        "简体中文"
	LanguageUpdated=                     "语言偏好已更新"
	Logout_Done=                         "已从FastBuilder用户中心退出登录。"
	Menu_BackButton=                     "< 返回"
	Menu_Cancel=                         "取消"
	Menu_CurrentPath=                    "当前路径"
	Menu_ExcludeCommandsOption=          "排除命令方块内容"
	Menu_GetEndPos=                      "获取终点坐标"
	Menu_GetPos=                         "获取坐标"
	Menu_InvalidateCommandsOption=       "命令无效化"
	Menu_Quit=                           "退出程序"
	Menu_StrictModeOption=               "严格模式"
	NotAnACMEFile=                       "所提供的文件不是ACME建筑文件"
	Notice_CheckUpdate=                  "正在检查更新，请稍等…"
	Notice_iSH_Location_Service=         "您正在使用iSH模拟器，定位权限需要被用于保持后台运行，除此之外没有任何定位数据被记录或使用，您可以随时关闭它。"
	Notice_OK=                           "完成\n"
	Notice_UpdateAvailable=              "有新的PhoenixBuilder版本（%s）可用。\n"
	Notice_UpdateNotice=                 "请更新本软件。\n"
	Notice_ZLIB_CVE=                     "您的zlib版本（%s）包含已被证实的严重漏洞，我们建议您更新它，以免发生意外"
	Notify_NeedOp=                       "需要 OP 权限以正常工作。"
	Notify_TurnOnCmdFeedBack=            "需要 sendcommandfeedback 为 true，我们已经为你打开该选项，使用完后请按需关闭"
	Omega_WaitingForOP=                  "Omega系统正在等待 OP 权限"
	Omega_Enabled=                       "Omega系统已启用！"
	OpPrivilegeNotGrantedForOperation=   "未授予机器人 OP 权限，请授予 OP 权限后再进行此操作"
	Parsing_UnterminatedEscape=          "转义未终止"
	Parsing_UnterminatedQuotedString=    "字符串引号部分未终止"
	PositionGot=                         "已获得到起点坐标"
	PositionGot_End=                     "已获得终点坐标"
	PositionSet=                         "已设定坐标"
	PositionSet_End=                     "已设定终点坐标"
	QuitCorrectly=                       "正常退出"
	Sch_FailedToResolve=                 "未能解析文件"
	SelectLanguageOnConsole=             "请在控制台中选择新语言"
	ServerCodeTrans=                     "服务器号"
	SimpleParser_Int_ParsingFailed=      "解析器：未能处理整数形参数"
	SimpleParser_InvEnum=                "解析器：无效枚举值，可用值有：%s."
	SimpleParser_Invalid_decider=        "解析器：无效决定子"
	SimpleParser_Too_few_args=           "解析器：参数过少"
	Special_Startup=                     "已启用语言：简体中文\n"
	SysError_EACCES=             "权限拒绝，请检查是否已经允许该程序访问对应文件。"
	SysError_EBUSY=              "文件被占用，请稍后再试。"
	SysError_EINVAL=             "无效文件输入。"
	SysError_EISDIR=             "输入文件为目录，无效输入。"
	SysError_ENOENT=             "对应文件不存在。"
	SysError_ETXTBSY=            "文件被占用，请稍后再试。"
	SysError_HasTranslation=     "对于 %s 的文件操作出错：%s"
	TaskCreated=                 "任务已创建"
	TaskDisplayModeSet=          "任务状态显示模式已经设置为= %s."
	TaskFailedToParseCommand=    "未能解析命令= %v"
	TaskNotFoundMessage=         "未能根据所提供的任务ID找到有效任务。"
	TaskPausedNotice=            "[任务 %d] - 已暂停"
	TaskResumedNotice=           "[任务 %d] - 已恢复"
	TaskStateLine=               "ID %d - 命令行=\"%s\" 状态= %s 延迟值= %d 延迟模式= %s 延迟阈值= %d"
	TaskStoppedNotice=           "[任务 %d] - 已停止"
	TaskTTeIuKoto=               "任务"
	TaskTotalCount=              "总数：%d"
	TaskTypeCalculating=         "正在计算"
	TaskTypeDied=                "已死亡"
	TaskTypePaused=              "已暂停"
	TaskTypeRunning=             "运行中"
	TaskTypeSpecialTaskBreaking= "特殊任务=正在终止"
	TaskTypeSwitchedTo=          "任务创建类型已经切换为：%s."
	TaskTypeUnknown=             "未知"
	Task_D_NothingGenerated=     "[任务 %d] 无任何结构成功生成。"
	Task_DelaySet=               "[任务 %d] - 延迟已设置= %d"
	Task_ResumeBuildFrom=        "从第 %v 个方块处恢复构建"
	Task_SetDelay_Unavailable=   "[setdelay] 在 none 延迟模式下不可用"
	Task_Summary_1=              "[任务 %d] %v 个方块被更改。"
	Task_Summary_2=              "[任务 %d] 用时= %v 秒"
	Task_Summary_3=              "[任务 %d] 平均速度= %v 方块/秒"
	UnsupportedACMEVersion=      "不支持该版本ACME结构（仅支持acme 1.2文件版本）"
	Warning_ACME_Deprecated=     "警告 - `acme' 功能已弃用且已移除，请迁移到BDX格式。详见 https=//github.com/LNSSPsd/PhoenixBuilder/issues/313"
	Warning_Schem_Deprecated=    "警告 - `schem' 功能已弃用且已移除，请迁移到BDX格式。详见 https=//github.com/LNSSPsd/PhoenixBuilder/issues/313"
	Warning_UserHomeDir=         "警告 - 无法获取当前用户主目录，将设定homedir=\".\";\n"

class language_US:
	message_1 = "This file is just a tribute to our missed PhonixBuilder"
	ACME_FailedToGetCommand=             "Failed to get acme command."
	ACME_FailedToSeek=                   "Invalid acme file since seek was failed."
	ACME_StructureErrorNotice=           "Invalid structure"
	ACME_UnknownCommand=                 "Unknown ACME command"
	Auth_BackendError=                   "Backend Error"
	Auth_FailedToRequestEntry=           "Failed to request entry for your server please check whether the password is correct and please turn off the level limitation"
	Auth_HelperNotCreated=               "Helper user haven't been created please go create it on FastBuilder User Center."
	Auth_InvalidFBVersion=               "Invalid FastBuilder version please update."
	Auth_InvalidHelperUsername=          "Invalid username for helper user please set it on FastBuilder User Center."
	Auth_InvalidToken=                   "Invalid login token."
	Auth_InvalidUser=                    "Invalid user for FastBuilder User Center"
	Auth_ServerNotFound=                 "Server not found please check your server's public state"
	Auth_UnauthorizedRentalServerNumber= "Unauthorized rental server number please add it on your FastBuilder User Center."
	Auth_UserCombined=                   "Given user has been combined to another account please login using another account's information."
	Auth_FailedToRequestEntry_TryAgain=  "Failed to request server entry please try again later."
	BDump_Author=                        "Author"
	BDump_EarlyEOFRightWhenOpening=      "Failed to read file early EOF? File may be corrupted"
	BDump_FailedToGetCmd1=               "Failed to get any argument for cmd[pos=0] file may corrupted"
	BDump_FailedToGetCmd2=               "Failed to get any argument for cmd[pos1] file may corrupted"
	BDump_FailedToGetCmd4=               "Failed to get any argument for cmd[pos2] file may corrupted"
	BDump_FailedToGetCmd6=               "Failed to get any argument for cmd[pos3] file may corrupted"
	BDump_FailedToGetCmd7_0=             "Failed to get any argument for cmd[pos4] file may corrupted"
	BDump_FailedToGetCmd7_1=             "Failed to get any argument for cmd[pos5] file may corrupted"
	BDump_FailedToGetCmd10=              "Failed to get any argument for cmd[pos6] file may corrupted"
	BDump_FailedToGetCmd11=              "Failed to get any argument for cmd[pos7] file may corrupted"
	BDump_FailedToGetCmd12=              "Failed to get any argument for cmd[pos8] file may corrupted"
	BDump_FailedToGetConstructCmd=       "Failed to get construction commands file may corrupted"
	BDump_FailedToReadAuthorInfo=        "Failed to read author info file may be corrupted"
	BDump_FileNotSigned=                 "File is not signed"
	BDump_FileSigned=                    "File is signed signer: %s"
	BDump_NotBDX_Invheader=              "Not a bdx file (Invalid file header)"
	BDump_NotBDX_Invinnerheader=         "Not a bdx file (Invalid inner file header)"
	BDump_SignedVerifying=               "File is signed verifying..."
	BDump_VerificationFailedFor=         "Failed to verify the file's signature due to: %v"
	BDump_Warn_Reserved=                 "WARNING: BDump/Import: Use of reserved command\n"
	CommandNotFound=                     "Command not found."
	ConnectionEstablished=               "Successfully created minecraft dialer."
	Copyright_Notice_Bouldev=            "Copyright (c) FastBuilder DevGroup Bouldev 2022"
	Copyright_Notice_Contrib=            "Contributors: Ruphane CAIMEO CMA2401PT"
	Crashed_No_Connection=               "connection not established after very long time"
	Crashed_OS_Windows=                  "Press ENTER to exit."
	Crashed_StackDump_And_Error=         "Stack dump was shown above error:"
	Crashed_Tip=                         "Oh no! FastBuilder Phoenix crashed!"
	CurrentDefaultDelayMode=             "Current default delay mode"
	CurrentTasks=                        "Current tasks:"
	DelayModeSet=                        "Delay mode set"
	DelayModeSet_DelayAuto=              "Delay automatically set to: %d"
	DelayModeSet_ThresholdAuto=          "Delay threshold automatically set to: %d"
	DelaySet=                            "Delay set"
	DelaySetUnavailableUnderNoneMode=    "[delay set] is unavailable with delay mode: none"
	DelayThreshold_OnlyDiscrete=         "Delay threshold is only available with delay mode: discrete"
	DelayThreshold_Set=                  "Delay threshold set to: %d"
	ERRORStr=                            "ERROR"
	EnterPasswordForFBUC=                "Enter your password for FastBuilder User Center: "
	Enter_FBUC_Username=                 "Enter your FastBuilder User Center username: "
	Enter_Rental_Server_Code=            "Please enter your rental server number: "
	Enter_Rental_Server_Password=        "Enter Password (Press [Enter] if not set input won't be echoed): "
	ErrorIgnored=                        "Error ignored."
	Error_MapY_Exceed=                   "In 3DMap MapY should be in [20~255] (Your Input : %v)"
	FBUC_LoginFailed=                    "Incorrect username or password"
	FBUC_Token_ErrOnCreate=              "Error creating token file: "
	FBUC_Token_ErrOnGen=                 "Failed to generate temp token"
	FBUC_Token_ErrOnRemove=              "Failed to remove token file: %v"
	FBUC_Token_ErrOnSave=                "Error saving token: "
	FileCorruptedError=                  "File is corrupted"
	Get_Warning=                         ""
	IgnoredStr=                          "ignored"
	InvalidFileError=                    "Invalid file"
	InvalidPosition=                     "No position got. (ignorable)"
	Lang_Config_ErrOnCreate=             "Error creating language config file: %v"
	Lang_Config_ErrOnSave=               "Error saving language config: %v"
	LanguageName=                        "American English"
	LanguageUpdated=                     "Language preference has been updated"
	Logout_Done=                         "Logged out from FastBuilder User Center."
	Menu_BackButton=                     "< Back"
	Menu_Cancel=                         "Cancel"
	Menu_CurrentPath=                    "Current path"
	Menu_ExcludeCommandsOption=          "Exclude Commands"
	Menu_GetEndPos=                      "getEndPos"
	Menu_GetPos=                         "getPos"
	Menu_InvalidateCommandsOption=       "Invalidate Commands"
	Menu_Quit=                           "Quit Program"
	Menu_StrictModeOption=               "Strict Mode"
	NotAnACMEFile=                       "Invalid file not an ACME structure."
	Notice_CheckUpdate=                  "Checking update please wait..."
	Notice_iSH_Location_Service=         "You are using iSH simulator location service is required for foreground no location data will be saved or used. You can terminate it anytime."
	Notice_OK=                           "OK\n"
	Notice_UpdateAvailable=              "A newer version (%s) of PhoenixBuilder is available.\n"
	Notice_UpdateNotice=                 "Please update.\n"
	Notice_ZLIB_CVE=                     "Your zlib version (%s) is too old since it contains confirmed CVE vulnerability updating suggested"
	Notify_NeedOp=                       "FastBuilder requires operator privilege."
	Notify_TurnOnCmdFeedBack=            "FastBuilder requires gamerule sendcommandfeedback to be true we have already turn it on and remember to turn it off"
	Omega_WaitingForOP=                  "Omega System is Waiting for OP Privilege"
	Omega_Enabled=                       "Omega System Enabled!"
	OpPrivilegeNotGrantedForOperation=   "Op privilege not granted for this operation please grant bot op privilege"
	Parsing_UnterminatedEscape=          "Unterminated escape"
	Parsing_UnterminatedQuotedString=    "Unterminated quoted string"
	PositionGot=                         "Position got"
	PositionGot_End=                     "End Position got"
	PositionSet=                         "Position set"
	PositionSet_End=                     "End position set"
	QuitCorrectly=                       "Quit correctly"
	Sch_FailedToResolve=                 "Failed to resolve file"
	SelectLanguageOnConsole=             "Please select your new preferred language on console."
	ServerCodeTrans=                     "Server"
	SimpleParser_Int_ParsingFailed=      "Parser: failed to parse an int argument"
	SimpleParser_InvEnum=                "Parser: Invalid enum value allowed values are: %s."
	SimpleParser_Invalid_decider=        "Parser: Invalid decider"
	SimpleParser_Too_few_args=           "Parser: Too few arguments"
	Special_Startup=                     "Enabled language: English\n"
	TaskCreated=                         "Task Created"
	TaskDisplayModeSet=                  "Task status display mode set to: %s."
	TaskFailedToParseCommand=            "Failed to parse command: %v"
	TaskNotFoundMessage=                 "Couldn't find a valid task by provided task id."
	TaskPausedNotice=                    "[Task %d] - Paused"
	TaskResumedNotice=                   "[Task %d] - Resumed"
	TaskStateLine=                       "ID %d - CommandLine=\"%s\" State: %s Delay: %d DelayMode: %s DelayThreshold= %d"
	TaskStoppedNotice=                   "[Task %d] - Stopped"
	TaskTTeIuKoto=                       "Task"
	TaskTotalCount=                      "Total: %d"
	TaskTypeCalculating=                 "Calculating"
	TaskTypeDied=                        "Died"
	TaskTypePaused=                      "Paused"
	TaskTypeRunning=                     "Running"
	TaskTypeSpecialTaskBreaking=         "SpecialTask=Breaking"
	TaskTypeSwitchedTo=                  "Task creation type set to: %s."
	TaskTypeUnknown=                     "Unknown"
	Task_D_NothingGenerated=             "[Task %d] Nothing generated."
	Task_DelaySet=                       "[Task %d] - Delay set: %d"
	Task_ResumeBuildFrom=                "Resume Build From Block Number %v "
	Task_SetDelay_Unavailable=           "[setdelay] is unavailable with delay mode= none"
	Task_Summary_1=                      "[Task %d] %v block(s) have been changed."
	Task_Summary_2=                      "[Task %d] Time used: %v second(s)"
	Task_Summary_3=                      "[Task %d] Average speed: %v blocks/second"
	UnsupportedACMEVersion=              "Unsupported ACME structure version. Only acme file version 1.2 is supported."
	Warning_ACME_Deprecated=             "WARNING - `acme' is deprecated and has been removed please migrate to BDX format instead.\nSee https=//github.com/LNSSPsd/PhoenixBuilder/issues/313 for more informations."
	Warning_Schem_Deprecated=            "WARNING - `schem' is deprecated and has been removed please migrate to BDX format instead. \nSee https=//github.com/LNSSPsd/PhoenixBuilder/issues/313 for more informations."
	Warning_UserHomeDir=                 "WARNING - Failed to obtain the user's home directory. made homedir=\".\";\n"

def language(lang:str="zh_CN"):
	if lang == "zh_CN":
		return language_CN
	elif lang == "en_US":
		return language_US
	else:
		return language_CN